version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "3005:3005"  
    volumes:
      - .:/app

  website:
    build:
      context: .
      dockerfile: Dockerfile.website
    ports:
      - "3000:3000"
    volumes:
      - .:/app
